### ISSUE TITLE
AttributeError: 'GridEnv' object has no attribute 'canvas'

### ISSUE THREAD

**Issue by RoshanUpadhyay02** [Mohan-Zhang-u/rlgridworld#1]
Hi,
I tried to explore the library "rlgridworld" it shows error as:
            ==>AttributeError: 'GridEnv' object has no attribute 'canvas'

I have attached the screenshot for your reference. I also tried to correct the error. I have attached a pdf file for your reference.
Please solve this issue as soon as possible.
![Error_Screenshot](https://user-images.githubusercontent.com/90834830/225026513-d406eb28-a1b4-480f-9b35-7b4e001c19e6.png)
[Error_File - Jupyter Notebook.pdf](https://github.com/Mohan-Zhang-u/rlgridworld/files/10969518/Error_File.-.Jupyter.Notebook.pdf)
[Error_Resolved_in_Gridenv - Jupyter Notebook.pdf](https://github.com/Mohan-Zhang-u/rlgridworld/files/10969519/Error_Resolved_in_Gridenv.-.Jupyter.Notebook.pdf)

**Comment by Mohan-Zhang-u** [comment]
fixed. Thanks for pointing this out.
